# Build the Win32 dirlist plugin as a DLL
name: Build dirlist DLL

on:
  workflow_dispatch:          # manual trigger
  push:
    paths:
      - '.github/workflows/build-dirlist.yml'   # run on updates to this workflow
      - 'src/plugins/win32/dirlist/**'
  pull_request:
    paths:
      - '.github/workflows/build-dirlist.yml'   # run on workflow changes in PRs
      - 'src/plugins/win32/dirlist/**'

jobs:
  build-dirlist:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Build dirlist.vcxproj (Release x86)
        run: msbuild src\plugins\win32\dirlist\dirlist.vcxproj /p:Configuration=Release /p:Platform=x86 /p:PlatformToolset=v143

      - name: Upload dirlist.dll
        uses: actions/upload-artifact@v4
        with:
          name: dirlist-plugin
          path: bin\win32\plugin\dirlist.dll
