# Build the Win32 dirlist plugin as a DLL on every push or PR
name: Build dirlist DLL

on:
  push:
    paths:
      - 'src/plugins/win32/dirlist/**'
  pull_request:
    paths:
      - 'src/plugins/win32/dirlist/**'

jobs:
  build-dirlist:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) If you already have a VS .sln or .vcxproj in src/plugins/win32/dirlist,
      #    use the MSBuild action to build it:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'
      - name: Build dirlist.vcxproj (Release x64)
        run: msbuild src\plugins\win32\dirlist\dirlist.vcxproj /p:Configuration=Release /p:Platform=x64

      # 2) If you do *not* have a .vcxproj and want to compile "manually" with cl.exe,
      #    uncomment the block below and adjust include/source file names:
      # - name: Initialize VS environment
      #   shell: cmd
      #   run: '"%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=amd64'
      # - name: Compile dirlist.dll with cl
      #   shell: cmd
      #   run: |
      #     cl /LD ^
      #       /I src\include ^
      #       src\plugins\win32\dirlist\*.cpp ^
      #       /link /OUT:dirlist.dll

      # 3) (Alternative) build with MinGW via MSYS2
      # - name: Set up MSYS2
      #   uses: msys2/setup-msys2@v2
      #   with:
      #     update: true
      # - name: Install toolchain
      #   run: pacman -Sy --noconfirm mingw-w64-x86_64-toolchain
      #   shell: msys2 { msystem: MINGW64 }
      # - name: Build dirlist.dll with gcc
      #   shell: msys2 { msystem: MINGW64 }
      #   run: |
      #     gcc -shared \
      #       -I ./src/include \
      #       -o dirlist.dll \
      #       ./src/plugins/win32/dirlist/*.c

      - name: Upload dirlist.dll
        uses: actions/upload-artifact@v3
        with:
          name: dirlist-plugin
          path: |
            src\plugins\win32\dirlist\Release\dirlist.dll
            # or if you used one of the manual steps above, adjust path to ./dirlist.dll
